In [ ]:

import imgaug as ia
import imgaug.augmenters as iaa
import imageio
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage
import cv2
from google.colab.patches import cv2_imshow
from os import listdir
from random import *
import numpy as np


In [ ]:
#rotation
ia.seed(1)
path = '/content/drive/MyDrive/dataset/images/'

for file in listdir(path):
  image = imageio.imread(path+file)
  labelfile = file.replace('.JPG','.txt')
  f = open('/content/drive/MyDrive/dataset/labels/'+labelfile)
  boundingboxes = f.readlines()

  for i in range(len(boundingboxes)):
    boundingboxif = boundingboxes[i].split(" ")
    #print(boundingboxif)
    for j in range(len(boundingboxif)):
        x=float(boundingboxif[j])
        boundingboxif[j] = x
    boundingboxes[i] = boundingboxif
    #print(boundingboxes[i])
  boundingbox_newif = []
  for i in range(len(boundingboxes)):
    x_center = boundingboxes[i][1]
    y_center = boundingboxes[i][2]
    height=boundingboxes[i][4]*1536
    width=boundingboxes[i][3]*2048

    x_center_new = x_center*2048
    y_center_new = y_center*1536

    x1 = int(x_center_new - width/2)
    y1 = int(y_center_new - height/2)
    x2 = int(x_center_new + width/2)
    y2 = int(y_center_new + height/2)

    boundingbox_newif.append([int(boundingboxif[0]),x1,y1,x2,y2])
    
  ia_bounding_boxes = []
  for box in boundingbox_newif:
    ia_bounding_boxes.append(ia.BoundingBox(x1 = box[0], y1 = box[1], x2= box[2], y2=box[3]))
      
  bbs = ia.BoundingBoxesOnImage(ia_bounding_boxes, shape = image.shape)

  seq = iaa.Sequential([
    #iaa.Affine(rotate=random.randrange(5,120)),
    iaa.Affine(rotate=random.randrange(5,120)),
  ])

  image_aug, bbs_aug = seq(image=image, bounding_boxes = bbs)
  
  cv2.imwrite('/content/drive/MyDrive/dataset/augmentation/images/'+"aug__"+file,image_aug)
  f = open('/content/drive/MyDrive/dataset/augmentation/labels/'+"aug__"+labelfile, "w")
  for i in range(len(boundingbox_newif)):
    for j in range(5):
      if j==4:
        f.write(str(boundingbox_newif[i][j]))
      else:
        f.write(str(boundingbox_newif[i][j])+" ")
      print(str(i)+":" + str(boundingbox_newif[i][j]))
    f.write("\n")
  f.close()


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
0:3
0:0.119629
0:0.492188
0:0.733887
0:0.815755
0:3
0:0.057129
0:0.421875
0:0.699219
0:0.792969
0:3
0:0.143555
0:0.408203
0:0.752441
0:0.729818
0:3
0:0.101562
0:0.412109
0:0.724609
0:0.787109
0:3
0:0.112305
0:0.421224
0:0.762695
0:0.855469
0:3
0:0.329102
0:0.486328
0:0.824219
0:0.84375
0:3
0:0.36377
0:0.407552
0:0.893066
0:0.977865
0:3
0:0.078125
0:0.492188
0:0.703613
0:0.818359
0:3
0:0.165039
0:0.486328
0:0.758301
0:0.775391
0:3
0:0.114746
0:0.283203
0:0.78125
0:0.683594
0:3
0:0.19873
0:0.414062
0:0.811035
0:0.767578
0:3
0:0.114258
0:0.124349
0:0.847168
0:0.597656
0:3
0:0.313477
0:0.410156
0:0.818848
0:0.858073
0:3
0:0.303223
0:0.093099
0:0.894531
0:0.919271
0:3
0:0.29248
0:0.259115
0:0.835938
0:0.945312
0:3
0:0.058105
0:0.28776
0:0.753906
0:0.75651
0:3
0:0.209473
0:0.486328
0:0.721191
0:0.84375
0:3
0:0.077148
0:0.136719
0:0.814941
0:0.701823
0:3
0:0.027344
0:0.134115
0:0.771973
0:0.720052
0:3
0:0.150879
0:0.417318
0:0.792969
0:0.840495
0:3
0:0.0224

KeyboardInterrupt: ignored

In [ ]:
!mkdir /content/drive/MyDrive/dataset/augmentation/images_2/
!mkdir /content/drive/MyDrive/dataset/augmentation/labels_2/

In [ ]:
!rm -r /content/drive/MyDrive/dataset/augmentation/images_2/*.JPG
!rm -r /content/drive/MyDrive/dataset/augmentation/labels_2/*.txt

In [ ]:
#rotation
ia.seed(1)
path = '/content/drive/MyDrive/dataset/images/'

images = np.array(
    [ia.quokka(size=(64, 64)) for _ in range(32)],
    dtype=np.uint8
)
sometimes = lambda aug: iaa.Sometimes(0.5, aug)

for file in listdir(path):
  img = imageio.imread(path+file)
  labelfile = file.replace('.JPG','.txt')
  f = open('/content/drive/MyDrive/dataset/labels/'+labelfile)
  boundingboxes = f.readlines()

  for i in range(len(boundingboxes)):
    boundingboxif = boundingboxes[i].split(" ")
    #print(boundingboxif)
    for j in range(len(boundingboxif)):
      x=float(boundingboxif[j])
      boundingboxif[j] = x
    boundingboxes[i] = boundingboxif
  boundingbox_newif = []
  for i in range(len(boundingboxes)):
    x_center = boundingboxes[i][1]
    y_center = boundingboxes[i][2]
    height = boundingboxes[i][4]*1536
    width = boundingboxes[i][3]*2048

    x_center_new = x_center * 2048
    y_center_new = y_center * 1536
    cls = int(boundingboxif[0])
    x1 = int(x_center_new - width/2)
    y1 = int(y_center_new - height/2)
    x2 = int(x_center_new + width/2)
    y2 = int(y_center_new + height/2)
    # x1 = int(boundingboxes[i][1])* 2048
    # y1 = int(boundingboxes[i][2])* 1536
    # x2 = int(boundingboxes[i][3])* 2048
    # y2 = int(boundingboxes[i][4])* 1536
     #print(boundingboxes[i])
  # boundingbox_newif = []
  # for i in range(len(boundingboxes)):
  boundingbox_newif.append([cls,x1,y1,x2,y2])
    
  ia_bounding_boxes = []
  for box in boundingbox_newif:
    ia_bounding_boxes.append(ia.BoundingBox(x1 = box[1], y1 = box[2], x2= box[3], y2=box[4], label = box[0]))
  # ia_bounding_boxes.append(ia.BoundingBox(x1=x1, y1=y1, x2=x2, y2=y2, label= cls))      
  bbs = ia.BoundingBoxesOnImage(ia_bounding_boxes, shape = img.shape)
  seq = iaa.Sequential(
    [
        #
        # Apply the following augmenters to most images.
        #
      
        
            
        
        #iaa.Fliplr(0.5), # horizontally flip 50% of all images
        #iaa.Flipud(0.2), # vertically flip 20% of all images

        # colorAug
        # change color space
     
        

        #sometimes(iaa.WithHueAndSaturation(
        #  iaa.WithChannels(0, iaa.Add((0, 50)))
        #)),
     
        # change brightness 
        iaa.Multiply((0.5, 1.5), per_channel=0.5), 
        # crop some of the images by 0-10% of their height/width
        sometimes(iaa.Crop(percent=(0, 0.1))),
        iaa.SomeOf((0,2),
        [
          iaa.AddToHueAndSaturation((-150, 150), per_channel=True),
         # Change brightness of images (50-150% of original value).             
          iaa.WithColorspace(
          to_colorspace="HSV",
          from_colorspace="RGB",
          children=iaa.WithChannels(
          0,
          iaa.Add((0, 100))
            )
          ),
         ],
         random_order=True
        ),
        
        # Apply affine transformations to some of the images
        # - scale to 80-120% of image height/width (each axis independently)
        # - translate by -20 to +20 relative to height/width (per axis)
        # - rotate by -45 to +45 degrees
        # - shear by -16 to +16 degrees
        # - order: use nearest neighbour or bilinear interpolation (fast)
        # - mode: use any available mode to fill newly created pixels
        #         see API or scikit-image for which modes are available
        # - cval: if the mode is constant, then use a random brightness
        #         for the newly created pixels (e.g. sometimes black,
        #         sometimes white)
        sometimes(iaa.Affine(
            scale={"x": (0.8, 1.2), "y": (0.8, 1.2)},
            rotate=(-45, 45),
            shear=(-8, 8),
            order=[0, 1],
            cval=(0, 255),
            mode=ia.ALL
        )),
       
        #
        # Execute 0 to 5 of the following (less important) augmenters per
        # image. Don't execute all of them, as that would often be way too
        # strong.
        #
        iaa.SomeOf((0, 3),
            [
                # Convert some images into their superpixel representation,
                # sample between 20 and 200 superpixels per image, but do
                # not replace all superpixels with their average, only
                # some of them (p_replace).
                #sometimes(
                #    iaa.Superpixels(
                #        #p_replace=(0, 1.0),
                #        n_segments=(20, 200)
                #    )
                #),

                # Blur each image with varying strength using
                # gaussian blur (sigma between 0 and 3.0),
                # average/uniform blur (kernel size between 2x2 and 7x7)
                # median blur (kernel size between 3x3 and 11x11).
                #iaa.OneOf([
                #    iaa.GaussianBlur((0, 3.0)),
                #    iaa.AverageBlur(k=(2, 7)),
                #    iaa.MedianBlur(k=(3, 11)),
                #]),

                # Sharpen each image, overlay the result with the original
                # image using an alpha between 0 (no sharpening) and 1
                # (full sharpening effect).
                #iaa.Sharpen(alpha=(0, 1.0), lightness=(0.75, 1.5)),

                # Same as sharpen, but for an embossing effect.
                #iaa.Emboss(alpha=(0, 1.0), strength=(0, 2.0)),

                # Search in some images either for all edges or for
                # directed edges. These edges are then marked in a black
                # and white image and overlayed with the original image
                # using an alpha of 0 to 0.7.
                #sometimes(iaa.OneOf([
                #    iaa.EdgeDetect(alpha=(0, 0.7)),
                #    iaa.DirectedEdgeDetect(
                #        alpha=(0, 0.7), direction=(0.0, 1.0)
                #    ),
                #])),

                # Add gaussian noise to some images.
                # In 50% of these cases, the noise is randomly sampled per
                # channel and pixel.
                # In the other 50% of all cases it is sampled once per
                # pixel (i.e. brightness change).
                iaa.AdditiveGaussianNoise(
                    loc=0, scale=(0.0, 0.05*255), per_channel=0.5
                ),

                # Either drop randomly 1 to 10% of all pixels (i.e. set
                # them to black) or drop them on an image with 2-5% percent
                # of the original size, leading to large dropped
                # rectangles.
                iaa.OneOf([
                    iaa.Dropout((0.01, 0.1), per_channel=0.5),
                    iaa.CoarseDropout(
                        (0.01, 0.10), size_percent=(0.01, 0.03),
                        per_channel=0.2
                    ),
                ]),

                # Invert each image's channel with 5% probability.
                # This sets each pixel value v to 255-v.
                iaa.Invert(0.05, per_channel=True), # invert color channels

                # Add a value of -10 to 10 to each pixel.
                iaa.Add((-10, 10), per_channel=0.5),

                
                iaa.Fliplr(0.5),
                iaa.Flipud(0.2),
                
                # Improve or worsen the contrast of images.
                iaa.LinearContrast((0.5, 2.0), per_channel=0.5),

                # Convert each image to grayscale and then overlay the
                # result with the original with random alpha. I.e. remove
                # colors with varying strengths.
                #iaa.Grayscale(alpha=(0.0, 1.0)),

                # In some images move pixels locally around (with random
                # strengths).
                #sometimes(
                #    iaa.ElasticTransformation(alpha=(0.5, 3.5), sigma=0.25)
                #),

                # In some images distort local areas with varying strength.
                sometimes(iaa.PiecewiseAffine(scale=(0.01, 0.03)))
            ],
            # do all of the above augmentations in random order
            random_order=True
        )
    ],
    # do all of the above augmentations in random order
    random_order=True
  )

  image_aug, bbs_aug = seq(image=img, bounding_boxes = bbs)
  # image_after = bbs_aug.draw_on_image(image_aug, size = 2, color=[0, 0, 255])
  # res = np.hstack((img, image_after))
  # print(bbs_aug.bounding_boxes)
  # cv2_imshow(res)
  

  cv2.imwrite('/content/drive/MyDrive/dataset/augmentation/images_2/'+"aug__"+file,image_aug)
  
  f = open('/content/drive/MyDrive/dataset/augmentation/labels_2/'+"aug__"+labelfile, "w")

  f.write(str(bbs_aug.bounding_boxes[0].label)+" ")
  f.write(str(bbs_aug.bounding_boxes[0].x1/2048)+" ")
  f.write(str(bbs_aug.bounding_boxes[0].y1/1536)+" ")
  f.write(str(bbs_aug.bounding_boxes[0].x2/2048)+" ")
  f.write(str(bbs_aug.bounding_boxes[0].y2/1536))    
  f.close()
  

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
print()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
import cv2
import numpy as np
import imgaug as ia
import imgaug.augmenters as iaa
path = '/content/drive/MyDrive/dataset/images/'
for file in listdir(path):
  img = cv2.imread(path+file)
  labelfile = file.replace('.JPG','.txt')
  gt = np.loadtxt('/content/drive/MyDrive/dataset/labels/'+labelfile, dtype=np.int, delimiter = ',')
 
input_img = img[np.newaxis, :, :, :]
bbox = [ia.BoundingBox(x1 = gt[0], y1 = gt[1], x2 = gt[2], y2 = gt[3])]
 
seq = iaa.Sequential([
    iaa.Multiply((1.2, 1.5)),
    iaa.Affine(
        scale = (0.5, 0.7),
        rotate = 45)])
 
aug_img, aug_bbox = seq(images = input_img, bounding_boxes = bbox)
# draw = aug_bbox[0].draw_on_image(aug_img[0], size = 2, color = [0,0,255])
# res = np.hstack((img, draw))
# cv2.imshow('res', res)​

ValueError: ignored

In [ ]:
#d1_train_cutout  생성 (O)
#d1_val_cutout 생성 (o)

#d3_train_cutout (o)
#d3_val_cutout
import numpy as np
from os import listdir
from random import *
import  cv2
from google.colab.patches import cv2_imshow
#d1_images cutout 하기 
path ='/content/drive/MyDrive/dataset/images/'  #cutout을 추가하고 싶은 이미지가 있는 경로 
for file in listdir(path): #경로에 있는 파일 하나하나 
  cutout = cv2.imread(path+file) #사진 파일 1개 (cutout을 추가하고 싶은 원본사진)
  labelfile = file.replace('.JPG','.txt') 
  #그 원본사진의 boundingbox 정보가 있는 label file명(저는 사진과 파일명을 똑같이 했기 때문에 jpg->txt 교체만 해줬습니다) 
  label = open('/content/drive/MyDrive/dataset/labels/'+labelfile,'r') #label file을 open해서 읽는다 
  list=label.readline() #label 첫 줄 읽기 
  for i in range(1):#저는 cutout 이미지를 3개 만들고 싶어서 for문을 3번 실행시켰습니다.
    f = open('/content/drive/MyDrive/dataset/augmentation/labels/'+'cutout'+str(i)+'__'+labelfile,"w") # 새로운 라벨파일 저장 (사진 1장당 1개 - 이름 맞춰서 )
    while(list):#바운딩 박스 당 
      #print(str(i) +list)
      f.write(list) #바운딩 박스 정보를 새로운 라벨 파일에 적는다. 
      #print(list)
      list=list.split()
      x_center=float(list[1])
      y_center=float(list[2])
      height=float(list[4])*1536
      width=float(list[3])*2048
      x_center_new=x_center*1536
      y_center_new=y_center*2048
       #print(x_center_new,y_center_new)
      x1=uniform(x_center_new-width/2,x_center_new+width/4) 
      y1=uniform(y_center_new-height/2,y_center_new+height/4)
      mark=width/2
      x2=x1+mark
      y2=y1+mark
      x1=int(x1)
      x2=int(x2)
      y1=int(y1)
      y2=int(y2)
     #print(x1," ",y1," ",x2," ",y2)       
      cutout = cv2.rectangle(cutout, (x1, y1), (x2,y2), (0, 0, 0), cv2.FILLED)  #원래 있던 사진  + 박스추가 + 박스추가 ..
      list=label.readline() #다음 바운딩 박스를 위해 다음 줄을  읽는다.  
    f.close()
    #cv2_imshow(cutout)
    label = open('/content/drive/MyDrive/dataset/labels/'+labelfile,'r')
    list=label.readline()
    cv2.imwrite('/content/drive/My Drive/dataset/augmentation/images/'+'cutout'+str(i)+'__'+file,cutout)
    cutout = cv2.imread(path+file)
    #라벨 복사 

In [ ]:
#grayscale
import numpy as np
from os import listdir
from random import *
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image

path = '/content/drive/MyDrive/dataset/images/'
save_path='/content/drive/MyDrive/dataset/augmentation/images/grayscale'

for file in listdir(path):
  img = Image.open(path+file).convert('L')
  img_numpy = np.array(img,'uint8')
  cv2.imwrite(save_path+file, img_numpy)

In [ ]:
import numpy as np
from os import listdir
from random import *
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image

path = '/content/drive/MyDrive/dataset/images/'
for file in listdir(path):
  labelfile = file.replace('.JPG','.txt')
  label = open('/content/drive/MyDrive/dataset/labels/'+labelfile,"r")
  list = label.readline()
  f = open('/content/drive/MyDrive/dataset/labels/'+'grayscale__' + labelfile,"w")
  f.write(list)




